version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: finance_manager
      JWT_SECRET: rahasia_negara
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: finance_manager
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/migrations.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: