apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance-app
  template:
    metadata:
      labels:
        app: finance-app
    spec:
      containers:
      - name: finance-app
        image: finance-manager:latest
        ports:
        - containerPort: 8080
        env:
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: finance-config
                key: db-user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: finance-secret
                key: db-password
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: finance-config
                key: db-name
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: finance-config
                key: db-host
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: finance-config
                key: db-port
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: finance-secret
                key: jwt-secret
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: finance-config
                key: server-port

---
apiVersion: v1
kind: Service
metadata:
  name: finance-service
spec:
  type: LoadBalancer
  selector:
    app: finance-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080